### ISSUE TITLE
Github Action for IETF I-D

### ISSUE THREAD

**Issue by OR13** [mesur-io/post-quantum-signatures#1]
Eventually we probably want to move away from markdown2rfc to a proper github actions scripts.

See bbs+ repo for examples.

**Comment by brownoxford** [comment]
I took a quick look at https://github.com/w3c-ccg/ldp-bbs2020, but didn't see the examples. Am I looking in the right place?

**Comment by OR13** [comment]
https://github.com/decentralized-identity/bbs-signature (see workflows folder)

**Comment by mprorock** [comment]
this is really really close on #5 - workflow done, some editorial and link items to correct still

**Comment by brownoxford** [comment]
Closed by #5
