### ISSUE TITLE
Update spec development instructions

### ISSUE THREAD

**Issue by OR13** [mesur-io/post-quantum-signatures#12]
The readme instructions should assist a contributor in setting up, building and previewing local spec changes.

The instructions should work in all operating systems, or list the only supported OS.

**Comment by OR13** [comment]
Currently getting this error in macOS:

```
cat draft-post-quantum-jose.md  | mmark | lib/add-note.py | xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/Users/orie/.cache/xml2rfc --v2v3 /dev/stdin -o /dev/stdout >draft-post-quantum-jose.xml
bash: mmark: command not found
Error: Unable to parse the XML document: /dev/stdin
make: *** [draft-post-quantum-jose.xml] Error 1
make: *** Deleting file `draft-post-quantum-jose.xml'
```

**Comment by brownoxford** [comment]
@OR13 The last line of the readme currently reads

> Command line usage requires that you have the necessary software installed. [See the instructions](https://github.com/martinthomson/i-d-template/blob/main/doc/SETUP.md).

The linked instructions appear to only be for *nix-like operating systems (no Windows). Should we import those into this repo, or somehow make this line stand out more?

**Comment by OR13** [comment]
@brownoxford I just tried to commands in the readme and they failed on macOS.... they worked for me before (when we used docker).

I need the ability to preview changes locally to contribute.

All commands needed should be documented in the README.

**Comment by brownoxford** [comment]
Per our offline conversation, I will modify `README.md` to include basic instructions for building `txt` and `html` versions of the draft spec for local review by installing the latest `mmark` and `xml2rfc` on Linux and OSX and also by running the relevant docker commands.

**Comment by mprorock** [comment]
@brownoxford how we looking here - is this ok to close?

**Comment by brownoxford** [comment]
> @brownoxford how we looking here - is this ok to close?

No, this is still on my plate
