### ISSUE TITLE
JWK and JWA Fields

### ISSUE THREAD

**Issue by OR13** [mesur-io/post-quantum-signatures#22]
Consider:

```js
kty: 'PQK',
alg: 'CRYDI',
pset: '3',
x: 'mVahKoVifK...'
```

Do we really want the `pset` value encoded like this?

JWA / JWK layers are meant to abstract complexity from lower level crypto.

IMO, we should be registering thing such that you can switch on a single string field...

When you see:

`crv: 'Ed25519'` ...You know you will be using `alg: EdDSA`.

When you see:

`crv: 'secp256k1'` ...You know you will be using `alg: ES256K`.

When you see:

`crv: 'P256'` ...You know you will be using `alg: ES256`.

I think we want `alg: 'CRYDI3'` or `pset: 'CRYDI3'`

But not both in the JWK.

**Comment by OR13** [comment]
This issue is also blocking out ability to register multicodecs since we need a single name for the concept of "crv" in order to do that.

**Comment by mprorock** [comment]
resolved to go alg path, but also allow for pset to express details on parameters
