### ISSUE TITLE
Rename draft to conform to IETF naming conventions

### ISSUE THREAD

**Issue by selfissued** [mesur-io/post-quantum-signatures#36]
To submit to the COSE working group, the draft name must be of the form `draft-<lastname>-cose-<draftname>`. I'd suggest the identifier `draft-prorock-cose-post-quantum-signatures` or something similar.

Note that both the filename and the draft name in the markdown need to be changed.  The draft name in the markdown should become  `draft-prorock-cose-post-quantum-signatures-00`.

**Comment by mprorock** [comment]
Keeping this open until we shift from `-latest` to `-00`

**Comment by brownoxford** [comment]
We are using https://github.com/martinthomson/i-d-template to manage the editing of this draft, and it requires `-latest` or linting fails.

@selfissued, is the `-00` suffix a hard requirement instead of `-latest`?

**Comment by OR13** [comment]
tooling should be handling this automatically.

See https://github.com/json-web-proofs/json-web-proofs/blob/main/.github/workflows/publish.yml

**Comment by brownoxford** [comment]
@selfissued I've reviewed the repository that Orie linked above, and confirmed that it is using the same tooling that we are for managing the editing of the draft, and that it also uses draft naming in the markdown with "-latest" suffix.

Can you comment on the `draft-prorock-cose-post-quantum-signatures-latest` naming vs. `draft-prorock-cose-post-quantum-signatures-00` that you requested above?
