### ISSUE TITLE
Do we want to rename this repo?

### ISSUE THREAD

**Issue by brownoxford** [mesur-io/post-quantum-signatures#7]
It looks like we have settled on `post-quantum-jose` for the draft name, should we modify the repo name to match?

**Comment by OR13** [comment]
i suggest keeping the name as is... and leaving the door open for COSE.

**Comment by OR13** [comment]
I suggest we drop jose from all the file names.

**Comment by brownoxford** [comment]
> 

Were you thinking we should go back to `post-quantum-signatures`, or something different?

**Comment by OR13** [comment]
the repo name is fine... I would build a single `draft-post-quantum-signatures` spec in it for now.

**Comment by brownoxford** [comment]
Sounds good - will put in a PR when other outstanding PRs for the draft body have been resolved.
