### ISSUE TITLE
Update Editors, Authors and Contributors

### ISSUE THREAD

**Issue by mprorock** [mesur-io/post-quantum-signatures#9]
- [x] spec has no more than 5 editors
- [x] spec editors contact information has been confirmed
- [x] additional contributors added to the acknowledgement section

@OR13 can you break apart editors on the top line from the additional contributors per some feedback from IETF folks

**Comment by OR13** [comment]
See [guidelines](https://www.ietf.org/standards/ids/guidelines/).
